### ISSUE TITLE
Page reload redirects to docs-page

### ISSUE THREAD

**Issue by jonasgeiler** [devRant-Community/API-Docs#1]
If I go to playground and refresh, I am redirected to the docs page

**Comment by jonasgeiler** [comment]
Okay I did it but now it's doing 3 redirects... But hey it works!

**Comment by cozyplanes** [comment]
What a lazy programmer... ^^

**Comment by jonasgeiler** [comment]
@cozyplanes If you look at the commits you can see that I've tried all sorts of things haha
