### ISSUE TITLE
Use package.json for dependencies

### ISSUE THREAD

**Issue by nblackburn** [devRant-Community/API-Docs#7]
At the moment, the projects dependencies are listed inside `/app/lib`. Moving dependencies into a `package.json` file is a well defined standard in modern day development practicses and should really be used going forwards.

**Comment by jonasgeiler** [comment]
I know that but I use GitHub Pages and from my knowledge it's not possible to use npm here.
Or do you mean uploading the complete node_modules folder to GitHub?

**Comment by nblackburn** [comment]
@Skayo i would build the package and upload that to a branch which is used by GitHub pages.

**Comment by jonasgeiler** [comment]
Okay I'll put that on my Todo List. Maybe will do later. For now I keep it as it is. (Till I finished the site)

**Comment by nblackburn** [comment]
That commit doesn't address this issue

**Comment by jonasgeiler** [comment]
Shit

**Comment by nblackburn** [comment]
Don't worry, these things happen.

**Comment by jonasgeiler** [comment]
Yeah it was meant to be #8 haha

**Comment by jonasgeiler** [comment]
Doing a complete remake therefore not needed anymore
